### ISSUE TITLE
At page 54 ,  investigate zero balances as a feature of fraud detection

### ISSUE THREAD

**Issue by CTSteven** [PacktPublishing/Machine-Learning-for-Finance#1]
Hi, 

  At page 54 of this book, there is a formula for counting origin accounts have insufficient funds. As the code below:

         len(dfOdd[(dfOdd.oldBalanceOrig <= dfOdd.amount)]) / len(dfOdd)

   This formula get 0.89664...  ,  close to 90% of the odd transactions have insufficient funds.
    Since we want accounts of insufficient funds before transaction.  why use  " <= "  not. " < " ?  
    ( The latter one get 0.21762...  )

Regards,
Steven

**Comment by JannesKlaas** [comment]
Hey Steven, thanks for investigating that! It is quite interesting that the difference between <= and < is so large here. "<" is a perfectly valid choice and it might actually be a better choice. It boils down to how you define insufficient, here we defined a transaction that would take the account to exactly zero as insufficient. Weather that is a good definition is up for debate of course, and most likely depends on the business context.

The point which the book aims to demonstrate here remains the same though, which is that we might find some interesting, sometimes odd, correlations in our data and need to be creative and vigilant about creating features.

**Comment by CTSteven** [comment]
Hi Jannes,
  
Thank you for your detailed and clear explanation. 

BR,
Steven
